export default {
  // auth actions
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER',
  EXPIRE_SESSION: 'EXPIRE_SESSION',

  // navigation actions
  NAVIGATE: 'Navigation/NAVIGATE',
  NAVIGATE_BACK: 'Navigation/BACK',
  NAVIGATION_RESET: 'Navigation/RESET',
  SET_ACTIVE_SCREEN: 'SET_ACTIVE_SCREEN',

  // form actions
  UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD',
  UPDATE_FORM_FIELDS: 'UPDATE_FORM_FIELDS',
  INIT_FORM: 'INIT_FORM',
  CLEAR_FORM: 'CLEAR_FORM',
  SET_FORM_ERRORS: 'SET_FORM_ERRORS',
  CLEAR_FORM_ERRORS: 'CLEAR_FORM_ERRORS',

  // camera actions
  TOGGLE_CAMERA: 'TOGGLE_CAMERA',
  FLIP_CAMERA: 'FLIP_CAMERA',
  TAKE_CAMERA_PHOTO: 'TAKE_CAMERA_PHOTO',
  RETAKE_PHOTO: 'RETAKE_PHOTO',
  ACTIVATE_CAMERA: 'ACTIVATE_CAMERA',
  DEACTIVATE_CAMERA: 'DEACTIVATE_CAMERA',

  // cameraRoll actions
  GET_CAMERA_ROLL_SUCCESS: 'GET_CAMERA_ROLL_SUCCESS',

  // api actions
  START_API_CALL: 'START_API_CALL',
  API_ERROR: 'API_ERROR',

  // lands actions
  GET_ALL_LANDS: 'GET_ALL_LANDS',
  GET_LAND_DETAILS: 'GET_LAND_DETAILS',
  GET_REPORT_DETAILS: 'GET_REPORT_DETAILS',
  GET_WEATHER: 'GET_WEATHER'
}
