export default {
  // auth api calls
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',

  // user api calls
  GET_USER_PERSONAL_INFO: 'GET_USER_PERSONAL_INFO',

  // camera roll calls
  GET_CAMERA_ROLL: 'GET_CAMERA_ROLL',
  TAKE_CAMERA_PHOTO: 'TAKE_CAMERA_PHOTO',

  // lands calls
  GET_ALL_LANDS: 'GET_ALL_LANDS',
  GET_LAND_DETAILS: 'GET_LAND_DETAILS',
  GET_REPORT_DETAILS: 'GET_REPORT_DETAILS',
  GET_GRAPH: 'GET_GRAPH',
  GET_RAIN_GRAPH: 'GET_RAIN_GRAPH'
}
