import React from 'react'
import { TouchableOpacity, Image, View, FlatList } from 'react-native'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import moment from 'moment'

import * as appActions from '../../../redux/actions'
import RegularLayout from '../../layouts/RegularLayout/RegularLayout'
import MyText from '../../atoms/MyText/MyText'
import Card from '../../atoms/Card/Card'
import Separator from '../../atoms/Separator/Separator'
import STYLES from '../../../constants/STYLES'
import TabBarIcon from '../../TabBarIcon'

const data = {
  id: 1,
  image: 'http://www.ekapija.com/thumbs/njiva_traktor_131216_tw630.jpg',
  name: 'Njiva 1',
}

@connect(
  () => ({}),
  dispatch => ({ actions: bindActionCreators(appActions, dispatch) })
)
export default class ReportDetails extends React.Component {
  static navigationOptions = () => ({
    title: 'Lands',
  })

  getStatusByType = status => {
    switch (status) {
      case 'pending':
        return (
          <MyText align="right" color={STYLES.COLORS.ORANGE}>
            Pending
          </MyText>
        )
      case 'diseased':
        return (
          <MyText align="right" color={STYLES.COLORS.RED}>
            Diseased
          </MyText>
        )
      default:
        return (
          <MyText align="right" color={STYLES.COLORS.MAIN_COLOR}>
            Healthy
          </MyText>
        )
    }
  }

  render() {
    const { actions } = this.props
    const LandList = this.renderLandsList
    const item = {
      id: '1',
      name: 'report 1',
      status: 'diseased',
      date: '11.5.2019',
    }
    const status = this.getStatusByType(item.status)
    const time = moment(item.date).isSame(moment(), 'day')
      ? moment(item.date, 'DD.MM.YYYY').format('HH:mm')
      : moment(item.date, 'DD.MM.YYYY').format('DD MMM YYYY')

    return (
      <RegularLayout>
        <>
          <MyText type="H2" align="center" margin="0 0 20 0">
            {item.name}
          </MyText>
          <Image
            style={{ flex: 1, height: 200, marginBottom: 20, borderRadius: 8 }}
            resizeMode="cover"
            source={{
              uri:
                'http://seebiz.eu:8080/upload/seebiz_eu/upload/sc_autogenerated_PART_3/article/ar_188163/poljoprivreda_soja_1468_0_0_468X10000.jpg',
            }}
          />
          {item.status === 'diseased' && (
            <Card color={STYLES.COLORS.DARK_GRAY_OPACITY}>
              <MyText>
                <TabBarIcon name="ios-warning" color={STYLES.COLORS.RED} />{' '}
                Prskaj druze
              </MyText>
            </Card>
          )}
          <View style={{ flexDirection: 'row', flex: 1, marginTop: 20 }}>
            <MyText style={{ flex: 1 }}>Date:</MyText>
            <MyText style={{ flex: 1 }} align="right">
              {time}
            </MyText>
          </View>
          <Separator margin="20 0 20 0" />
          <View style={{ flexDirection: 'row' }}>
            <MyText style={{ flex: 1 }}>Status:</MyText>
            {status}
          </View>
        </>
      </RegularLayout>
    )
  }
}
