import React from 'react'
import { TouchableOpacity, Image, View, FlatList } from 'react-native'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import moment from 'moment'

import * as appActions from '../../../redux/actions'
import RegularLayout from '../../layouts/RegularLayout/RegularLayout'
import MyText from '../../atoms/MyText/MyText'
import Card from '../../atoms/Card/Card'
import Separator from '../../atoms/Separator/Separator'
import STYLES from '../../../constants/STYLES'
import TabBarIcon from '../../TabBarIcon'

@connect(
  state => ({
    reportDetails: state.lands.reportDetails,
  }),
  dispatch => ({ actions: bindActionCreators(appActions, dispatch) })
)
export default class ReportDetails extends React.Component {
  static navigationOptions = () => ({
    title: 'Report',
  })

  componentDidMount() {
    const { actions, navigation } = this.props
    const reportID = navigation.getParam('reportID')
    actions.getReportDetails(reportID)
  }

  getStatusByType = status => {
    switch (status) {
      case 'pending':
        return (
          <MyText align="right" color={STYLES.COLORS.ORANGE}>
            Pending
          </MyText>
        )
      case 'diseased':
        return (
          <MyText align="right" color={STYLES.COLORS.RED}>
            Diseased
          </MyText>
        )
      default:
        return (
          <MyText align="right" color={STYLES.COLORS.MAIN_COLOR}>
            Healthy
          </MyText>
        )
    }
  }

  render() {
    const { reportDetails } = this.props
    const status = this.getStatusByType(reportDetails.status)
    const time = moment(reportDetails.date).isSame(moment(), 'day')
      ? moment(reportDetails.date, 'DD.MM.YYYY').format('HH:mm')
      : moment(reportDetails.date, 'DD.MM.YYYY').format('DD MMM YYYY')
    console.log('reportDetails', reportDetails)
    return (
      <RegularLayout>
        <>
          <MyText type="H2" align="center" margin="0 0 20 0">
            {reportDetails.parent.name}
          </MyText>
          <Image
            style={{ flex: 1, height: 200, marginBottom: 20, borderRadius: 8 }}
            resizeMode="cover"
            source={{
              uri:
                'http://seebiz.eu:8080/upload/seebiz_eu/upload/sc_autogenerated_PART_3/article/ar_188163/poljoprivreda_soja_1468_0_0_468X10000.jpg',
            }}
          />
          {reportDetails.status === 'diseased' && (
            <Card color={STYLES.COLORS.DARK_GRAY_OPACITY}>
              <MyText>
                <TabBarIcon name="ios-warning" color={STYLES.COLORS.RED} />{' '}
                Prskaj druze
              </MyText>
            </Card>
          )}
          <View style={{ flexDirection: 'row', flex: 1, marginTop: 20 }}>
            <MyText style={{ flex: 1 }}>Date:</MyText>
            <MyText style={{ flex: 1 }} align="right">
              {time}
            </MyText>
          </View>
          <Separator margin="20 0 20 0" />
          <View style={{ flexDirection: 'row' }}>
            <MyText style={{ flex: 1 }}>Status:</MyText>
            {status}
          </View>
        </>
      </RegularLayout>
    )
  }
}
